org: dorelljames
service: webriqforms-serverless

custom:
  WF_Forms_TableName: "webriqforms-forms-table-${self:provider.stage}"
  WF_FormSubmissions_TableName: "webriqforms-form_submissions-table-${self:provider.stage}"
  WF_FormNonces_TableName: "webriqforms-form_nonces-table-${self:provider.stage}"
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}
  dynamodb:
    stages:
      - ${self:provider.stage}
    start:
      migrate: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["FormsDynamoDBTable", "Arn"] }
        - { "Fn::GetAtt": ["SubmissionsDynamoDBTable", "Arn"] }
        - { "Fn::GetAtt": ["FormNoncesDynamoDBTable", "Arn"] }
  environment:
    FORMS_TABLE: ${self:custom.WF_Forms_TableName}
    FORMNONCES_TABLE: ${self:custom.WF_FormNonces_TableName}
    FORM_SUBMISSIONS_TABLE: ${self:custom.WF_FormSubmissions_TableName}
    APP_URL: https://forms.webriq.com
    APP_STAGE: ${self:custom.stage}
    APP_DEFAULT_RECAPTCHA_KEY: 6Lc0DGoUAAAAAMVQyBWYOoBPROnXpLoK1vvF_vx8
    APP_DEFAULT_RECAPTCHA_SECRET: 6Lc0DGoUAAAAAEwAwSrku8PZ_eNRb_wtQtENx-S4
    CLOUDINARY_CLOUD_NAME: dokfyxs4e
    CLOUDINARY_API_KEY: 151834162875131
    CLOUDINARY_API_SECRET: 3cxSNFjBmJRNjOrOVBweYgx-ZgQ
    MAILGUN_USER: postmaster@mg.foodhunt.today
    MAILGUN_PASSWORD: 4e38973f926ff10889b69de7ebaf2d56
    MAILTRAP_USER: 44314661af65a2928
    MAILTRAP_PASSWORD: 093bfd51adeb42
    WEBRIQ_FORMS_API_URL_DEV: http://localhost:3000/forms/
    WEBRIQ_FORMS_API_URL:
      {
        "Fn::Join":
          [
            "",
            [
              " https://",
              { "Ref": "ApiGatewayRestApi" },
              ".execute-api.${self:custom.region}.amazonaws.com/${self:custom.stage}/",
            ],
          ],
      }

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: "ANY {proxy+}"

  createForm:
    handler: index.handler
    events:
      - http: "POST /forms"
  getForms:
    handler: index.handler
    events:
      - http: "GET /forms"
  getForm:
    handler: index.handler
    events:
      - http: "GET /forms/{proxy+}"

  updateForm:
    handler: index.handler
    events:
      - http: "PUT /forms/{proxy+}"
  deleteForm:
    handler: index.handler
    events:
      - http: "DELETE /forms/{proxy+}"

  getJSLib:
    handler: index.handler
    events:
      - http: "GET /js/initForms"
  getReactJSLib:
    handler: index.handler
    events:
      - http: "GET /js/initReactForms"

plugins:
  - serverless-offline
  - serverless-dynamodb-local

resources:
  Resources:
    FormsDynamoDBTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: ${self:custom.WF_Forms_TableName}
        AttributeDefinitions:
          - AttributeName: _id
            AttributeType: S
        KeySchema:
          - AttributeName: _id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    SubmissionsDynamoDBTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: ${self:custom.WF_FormSubmissions_TableName}
        AttributeDefinitions:
          - AttributeName: _id
            AttributeType: S
          - AttributeName: _form
            AttributeType: S
        KeySchema:
          - AttributeName: _id
            KeyType: HASH
          - AttributeName: _form
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

    FormNoncesDynamoDBTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: ${self:custom.WF_FormNonces_TableName}
        AttributeDefinitions:
          - AttributeName: token
            AttributeType: S
        KeySchema:
          - AttributeName: token
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
