org: dorelljames
service: webriqforms-test2-withNonce-serverless

custom:
  WebriQ_Forms_TableName: "webriqforms-test2-withNonce-table-${self:provider.stage}"
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}
  dynamodb:
    stages:
      - ${self:provider.stage}
    start:
      migrate: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["WebriQFormsDynamoDBTable", "Arn"] }
  environment:
    WEBRIQ_FORMS_TABLE: ${self:custom.WebriQ_Forms_TableName}
    APP_URL: https://forms.webriq.com
    APP_STAGE: ${self:custom.stage}
    APP_DEFAULT_RECAPTCHA_KEY: 6Lc0DGoUAAAAAMVQyBWYOoBPROnXpLoK1vvF_vx8
    APP_DEFAULT_RECAPTCHA_SECRET: 6Lc0DGoUAAAAAEwAwSrku8PZ_eNRb_wtQtENx-S4
    CLOUDINARY_CLOUD_NAME: dokfyxs4e
    CLOUDINARY_API_KEY: 151834162875131
    CLOUDINARY_API_SECRET: 3cxSNFjBmJRNjOrOVBweYgx-ZgQ
    MAILGUN_USER: postmaster@webriqshops.com
    MAILGUN_PASSWORD: 0c7389efd226e9bee418cc83e73b0bfe
    MAILTRAP_USER: 44314661af65a2928
    MAILTRAP_PASSWORD: 093bfd51adeb42
    WEBRIQ_FORMS_API_URL_DEV: http://localhost:3000/forms/
    WEBRIQ_FORMS_API_URL:
      {
        "Fn::Join":
          [
            "",
            [
              " https://",
              { "Ref": "ApiGatewayRestApi" },
              ".execute-api.${self:custom.region}.amazonaws.com/${self:custom.stage}/",
            ],
          ],
      }

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: "ANY {proxy+}"

  getFormSubmissions:
    handler: index.handler
    events:
      - http: "GET /forms/{proxy}/submissions"
  getFormSubmission:
    handler: index.handler
    events:
      - http: "GET /forms/{proxy}/submissions/{id}"
  createFormSubmission:
    handler: index.handler
    events:
      - http: "POST /forms/{proxy}/submissions"
  deleteFormSubmission:
    handler: index.handler
    events:
      - http: "DELETE /forms/{proxy}/submissions/{id}"

  createForm:
    handler: index.handler
    events:
      - http: "POST /forms"
  getForms:
    handler: index.handler
    events:
      - http: "GET /forms"
  getFormByURL:
    handler: index.handler
    events:
      - http: "GET /forms/{proxy}/url"
  getForm:
    handler: index.handler
    events:
      - http: "GET /forms/{proxy}"

  updateForm:
    handler: index.handler
    events:
      - http: "PUT /forms/{proxy}"
  deleteForm:
    handler: index.handler
    events:
      - http: "DELETE /forms/{proxy}"

  getJSLib:
    handler: index.handler
    events:
      - http: "GET /js/initForms"
  getReactJSLib:
    handler: index.handler
    events:
      - http: "GET /js/initReactForms"

plugins:
  - serverless-offline
  - serverless-dynamodb-local

resources:
  Resources:
    WebriQFormsDynamoDBTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: ${self:custom.WebriQ_Forms_TableName}
        AttributeDefinitions:
          - AttributeName: _type
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: N
        KeySchema:
          - AttributeName: _type
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TimeToLiveSpecification:
          AttributeName: expiresAt
          Enabled: true
