service: my-express-application

custom:
  WF_Forms_TableName: "wf-forms-table-${self:provider.stage}"
  WF_FormSubmissions_TableName: "wf-submissions-table-${self:provider.stage}"
  WF_FormNonces_TableName: "wf-form_nonces-table-${self:provider.stage}"
  tableName: "users-table-${self:provider.stage}"
  dynamodb:
    stages:
      - ${self:provider.stage}
    start:
      migrate: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["UsersDynamoDBTable", "Arn"] }
        - { "Fn::GetAtt": ["FormsDynamoDBTable", "Arn"] }
        - { "Fn::GetAtt": ["SubmissionsDynamoDBTable", "Arn"] }
  environment:
    USERS_TABLE: ${self:custom.tableName}
    FORMS_TABLE: ${self:custom.WF_Forms_TableName}
    FORMNONCES_TABLE: ${self:custom.WF_FormNonces_TableName}
    SUBMISSIONS_TABLE: ${self:custom.WF_FormSubmissions_TableName}
    APP_URL: https://forms.webriq.com

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: "ANY {proxy+}"
  createForm:
    handler: index.handler
    events:
      - http: "POST /forms"
  getForms:
    handler: index.handler
    events:
      - http: "GET /forms"
  getForm:
    handler: index.handler
    events:
      - http: "GET /forms/{proxy+}"
  updateForm:
    handler: index.handler
    events:
      - http: "PUT /forms/{proxy+}"
  deleteForm:
    handler: index.handler
    events:
      - http: "DELETE /forms/{proxy+}"

plugins:
  - serverless-offline
  - serverless-dynamodb-local

resources:
  Resources:
    FormsDynamoDBTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: ${self:custom.WF_Forms_TableName}
        AttributeDefinitions:
          - AttributeName: _id
            AttributeType: S
        KeySchema:
          - AttributeName: _id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    SubmissionsDynamoDBTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: ${self:custom.WF_FormSubmissions_TableName}
        AttributeDefinitions:
          - AttributeName: _id
            AttributeType: S
        KeySchema:
          - AttributeName: _id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    FormNoncesDynamoDBTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: ${self:custom.WF_FormNonces_TableName}
        AttributeDefinitions:
          - AttributeName: _id
            AttributeType: S
        KeySchema:
          - AttributeName: _id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    UsersDynamoDBTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}
